### ISSUE TITLE
just tried to install it on windows

### ISSUE THREAD

**Issue by pythonmobile** [facebookarchive/huxley#1]
pip install huxley 
...

  File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 369, in add_
defaults

  File "build\bdist.win32\egg\setuptools\command\sdist.py", line 296, in read_ma
nifest

  File "build\bdist.win32\egg\setuptools\command\egg_info.py", line 284, in appe
nd

  File "c:\Python27\lib\distutils\util.py", line 124, in convert_path

```
raise ValueError, "path '%s' cannot be absolute" % pathname
```

ValueError: path '/' cannot be absolute

---

**Comment by petehunt** [comment]
Does `easy_install huxley` work? How about running the setup.py script directly from a checkout?

**Comment by cyildirim** [comment]
I have same problem with @pythonmobile . But i didnt take any error with @petehunt 's method. Thanks.

**Comment by pythonmobile** [comment]
I tried easy_install, and it complained that I did not have permission to write some file (I was in admin mode). Are you using PIL on this project? Have you tried pillows?

**Comment by pythonmobile** [comment]
Here is another problem I hit : (I could run it on debian)

Any ideas what is wrong? 

---

## Running Huxley file: Huxleyfile

Running test: toggle
Begin record
Press enter to take a screenshot, or type Q+enter if you're done
Q
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 9, in <module>
    load_entry_point('Huxley==0.2', 'console_scripts', 'huxley')()
  File "/usr/local/lib/python2.7/dist-packages/huxley/cmdline.py", line 126, in main
    sys.exit(plac.call(_main))
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/usr/local/lib/python2.7/dist-packages/plac_core.py", line 195, in consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/huxley/cmdline.py", line 105, in _main
    record=True
  File "/usr/local/lib/python2.7/dist-packages/huxley/main.py", line 109, in main
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "/usr/local/lib/python2.7/dist-packages/huxley/run.py", line 127, in record
    events = d.execute_script('return window._getHuxleyEvents();')
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 397, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u"window._getHuxleyEvents is not a function\nBuild info: version: '2.33.0', revision: '4e90c97', time: '2013-05-22 15:32:38'\nSystem info: os.name: 'Linux', os.arch: 'amd64', os.version: '3.2.0-4-amd64', java.version: '1.6.0_27'\nDriver info: driver.version: unknown" ; Screenshot: available via screen ; Stacktrace: Method anonymous threw an error in http://mydomain.com/~user

**Comment by djg10** [comment]
It worked when I installed it from the .zip file directly. I couldn't get it working using easy_install or pip.

**Comment by vinht23** [comment]
@djg10, Thanks for the tip. This install method works!

**Comment by petehunt** [comment]
I'll check out this issue further when I get back from vacation next week. Thank you guys for tracking down a workaround!

**Comment by rick-li** [comment]
@djg10 Hi, how do you install from .zip file, which zip file are you referring to? thanks!

**Comment by vinht23** [comment]
@rick-li You download the zip repository of Huxley. Then you unzip it and run setup.py install.

**Comment by petehunt** [comment]
I think this has been fixed. Please reopen if you see any issues; thanks!

**Comment by anth0nyc** [comment]
Win7 Pro Python34  - I am getting: NameError: name 'execfile' is not defined
note: also tried with Python 27 but it didn't have pip

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  Al

C:\Users\Z003BXMW>pip install huxley
Downloading/unpacking huxley
  Downloading Huxley-0.5.tar.gz
  Running setup.py (path:C:\Users\Z003BXMW\Ap
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "C:\Users\Z003BXMW\AppData\Local\T
        execfile(os.path.join(DIRNAME, 'huxle
    NameError: name 'execfile' is not defined
    Complete output from command python setup
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "C:\Users\Z003BXMW\AppData\Local\Temp\

```
execfile(os.path.join(DIRNAME, 'huxley',
```

NameError: name 'execfile' is not defined

**Comment by jigisha9** [comment]
I donot find zip file to download huxley from: https://github.com/facebook/huxley/tree/master/huxley
or https://github.com/facebook/huxley... can you send me link where this zip file resides?
