### ISSUE TITLE
Selenium can't detect buttons in modal panels

### ISSUE THREAD

**Issue by robfe11** [facebookarchive/huxley#11]
Hi,

I'm using the Twitter Bootstrap framework to display a simple modal panel with a button in it.  Huxley is able to record the test case where I open the modal, then click on the button.  However, during playback, it spits this error out (which is from Selenium):

```
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: Element is not currently visible and so may not be interacted with
Build info: version: '2.34.0', revision: '11cd0ef', time: '2013-08-06 17:10:22'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.8.4', java.version: '1.6.0_51'
Driver info: driver.version: unknown
    at <anonymous class>.fxdriver.preconditions.visible(file:///var/folders/1c/c828yyp916x8cxzgntwnt5fm0000gn/T/anonymous4476072821512445183webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:8230)
    at <anonymous class>.DelayedCommand.prototype.checkPreconditions_(file:///var/folders/1c/c828yyp916x8cxzgntwnt5fm0000gn/T/anonymous4476072821512445183webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:10799)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_/h(file:///var/folders/1c/c828yyp916x8cxzgntwnt5fm0000gn/T/anonymous4476072821512445183webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:10816)
    at <anonymous class>.DelayedCommand.prototype.executeInternal_(file:///var/folders/1c/c828yyp916x8cxzgntwnt5fm0000gn/T/anonymous4476072821512445183webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:10821)
    at <anonymous class>.DelayedCommand.prototype.execute/<(file:///var/folders/1c/c828yyp916x8cxzgntwnt5fm0000gn/T/anonymous4476072821512445183webdriver-profile/extensions/fxdriver@googlecode.com/components/command_processor.js:10763)
17:40:07.625 WARN - Exception: Element is not currently visible and so may not be interacted with
```

Doing a bit of investigation, looks like it might be an issues with the Selenium FF driver,  This might be related: 

http://stackoverflow.com/questions/17602334/element-is-not-currently-visible-and-so-may-not-be-interacted-with-but-another

Any idea how to resolve this?

Rob

**Comment by petehunt** [comment]
Cool find. I think this is a webdriver bug. I suppose it could be hacked around by hacking the DOM before each click (i.e. removing overflow:hidden anywhere in the parent), but this should really be fixed upstream, no?

I'd consider a PR for this, but I'm unsure what the implications of changing the layout like that would be (what happens if it changes where the click target is?) and I am not sure I can prioritize this right now. Is there a bug we could bump in webdriver?

**Comment by robfe11** [comment]
Actually, I spent a bit more time testing it, I think it's because we change the content within the modal after clicking the button.  Selenium thinks that the new content is still hidden, even though it's now visible.  
Modal in action can be found [here](http://buyable.me/product/view/98), just click the "Start watching" button, and enter a random e-mail address, then click submit.  The step after submit is where it fails.  

Also, I tested this using the Chrome driver instead, and it fails even before.  Looks like Selenium can't find the input box in the modal:

```
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 8, in <module>
    load_entry_point('Huxley==0.3', 'console_scripts', 'huxley')()
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 150, in main
    sys.exit(plac.call(_main))
  File "/Library/Python/2.7/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Library/Python/2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 127, in _main
    screensize=screensize
  File "/Library/Python/2.7/site-packages/huxley/main.py", line 109, in main
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 152, in record
    cls.rerecord(test, path, url, remote_d, sleepfactor, diffcolor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 75, in rerecord
    run._playback(sleepfactor)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 95, in _playback
    step.execute(self)
  File "/Library/Python/2.7/site-packages/huxley/steps.py", line 45, in execute
    run.d.find_element_by_id(id).click()
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 54, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webelement.py", line 228, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'unknown error: Element is not clickable at point (854, 42). Other element would receive the click: <div class="modal-backdrop fade in"></div>\n  (Session info: chrome=28.0.1500.95)\n 
```

**Comment by petehunt** [comment]
Hey @robfe11 - I ran into this today and just added c04a47951cb3e286dcafe568dbb5e2c04424ffbe which fixed it for my modal implementation. Can you reinstall from github and let me know if it works for you?

**Comment by robfe11** [comment]
Hi @petehunt, 

Thanks for making that change, recording works great now, but the playback now has an issue.  I am taking two screenshots, one after the modal appears, and then another one after the form submit in the modal (modal is still open).  The recording portion runs without any issues, but then the playback fails at the first screenshot:

```
Begin playback
  Sleeping for 1197.0 ms
  Clicking [967, 363]
  Sleeping for 1620.0 ms
  Typing A
  Sleeping for 416.0 ms
  Taking screenshot 0
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 8, in <module>
    load_entry_point('Huxley==0.3', 'console_scripts', 'huxley')()
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 150, in main
    sys.exit(plac.call(_main))
  File "/Library/Python/2.7/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Library/Python/2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 127, in _main
    screensize=screensize
  File "/Library/Python/2.7/site-packages/huxley/main.py", line 109, in main
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 152, in record
    cls.rerecord(test, path, url, remote_d, sleepfactor, diffcolor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 79, in rerecord
    cls.playback(test, path, url, d, sleepfactor, diffcolor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 85, in playback
    run._playback(sleepfactor)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 95, in _playback
    step.execute(self)
  File "/Library/Python/2.7/site-packages/huxley/steps.py", line 93, in execute
    raise TestError('Screenshot %s was different.' % self.index)
huxley.errors.TestError: Screenshot 0 was different.
```

The odd part is that when I run through the same test case, but only take that first screenshot, then do the playback, it executes without any issues.  

Any ideas?

**Comment by petehunt** [comment]
So when you record, Huxley will do playback twice to be sure that it'll work when you run it again. Did that process complete successfully or is that where this failure is coming from?

Also what may be helpful is running Huxley with the `--save-diff` option so you can identify exactly what's wrong.

**Comment by robfe11** [comment]
It fails in the second playback.  Didn't know about `--save-diff`, just ran it with that option, and the screenshots are different.  The modal opacity in screenshot0 is correct, whereas in screenshot1, there's no opacity.

![screenshot0](https://f.cloud.github.com/assets/780865/951270/541d3c16-039f-11e3-8516-139770360b86.png)
![screenshot1](https://f.cloud.github.com/assets/780865/951271/54323b98-039f-11e3-9a6e-c7d7dee1ed0c.png)

**Comment by petehunt** [comment]
I wonder if there are two modal masks stacked on top of each other?

**Comment by robfe11** [comment]
Just checked the CSS, there's only one.  Also, I was watching the FF windows are it was recording it, the modal panel shows up fine in the browser, but not in the screenshots.  It's really odd...

**Comment by robfe11** [comment]
On a side note, did you look into PhantomJS when selecting headless browsers?

**Comment by petehunt** [comment]
Does Phantom support screen shots? I tried it once and it came back a big gray square but I certainly may have screwed something up.

**Comment by robfe11** [comment]
Yah, it does, we use it for one of our projects, and it's a really good headless browser.  It supports all CSS selectors, and it's easy to retrieve data.  CasperJS (http://casperjs.org/) can run on top of it for scripting test cases ala Selenium.  I'm not sure how you would record user input though like you currently do for huxley (which is the huge timesaver).

**Comment by petehunt** [comment]
OK, so I am debugging a similar issue that came up with our modals today and the stuff I just pushed is working for me (we're using React though, not bootstrap). Maybe fetch from GitHub again and see if it works.

At Instagram we record using browsers on our laptops and then playback on a remote server. It appears that PhantomJS supports webdriver -- all you need to do is set the `HUXLEY_WEBDRIVER_REMOTE` environment variable to point to your Selenium server for PhantomJS and it should just work. If you get this running let me know!

**Comment by robfe11** [comment]
So I tried again using your latest code and the Selenium server, no dice.

I also spent the morning trying to get PhantomJS to play nice, but it didn't work.  The main reason is that PhantomJS is a headless browser (no UI), so the recording step doesn't work.  I was trying to hack around with your code to write the JSON file using FF, but then have PhantomJS do the actually playback.   

To get Huxley to connect to PhantomJS, I had to add a try/except block - https://github.com/robfe11/huxley/commit/8661ca4568f69e61e5fe5c57c2ad0b3b8121c91f   

After that, I tried a couple things:
- Running PhantomJS as a remote webdriver, it's easy enough using `/usr/local/bin/phantomjs --webdriver 8085`
  *\* Connection to it worked, but you are unable to record the steps since it's a headless browser 
- Running PhantomJS through Selenium grid hub, use `-role hub` when running the Selenium server, then `/usr/local/bin/phantomjs --webdriver 7001 --webdriver-selenium-grid-hub=http://127.0.0.1:4444` for phantomjs
  *\* Connection worked, but once again, couldn't record

Anyways, the above could be useful, if you want to ever move Huxley to work serverside.

Having said that, I figured out why Selenium was failing in the first place, and why the modal panel had 0 opacity.  For some reason Selenium is not selecting the right input box, and ends up using an input box that's behind the modal panel.  So maybe your latest selector code needs to be updated?

**Comment by petehunt** [comment]
So if PhantomJS supports `elementFromPoint()` and can take screenshots we should be able to record on Firefox and playback on Phantom. Did you try using Phantom only for playback (i.e. only changing `HUXLEY_WEBDRIVER_REMOTE`?) rather than for both?

So Selenium was sending keystrokes to the wrong input box?

**Comment by robfe11** [comment]
Yes, I did only change `HUXLEY_WEBDRIVER_REMOTE` but then FF wouldn't launch anymore.  I will try it again this afternoon.  

Yes, Selenium was sending the keystrokes to the input box behind the modal panel.

**Comment by robfe11** [comment]
So I tried again by just setting `HUXLEY_WEBDRIVER_REMOTE`, and it's throwing the following error on playback:

```
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 8, in <module>
    load_entry_point('Huxley==0.3', 'console_scripts', 'huxley')()
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 153, in main
    sys.exit(plac.call(_main))
  File "/Library/Python/2.7/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Library/Python/2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Library/Python/2.7/site-packages/huxley/cmdline.py", line 130, in _main
    screensize=screensize
  File "/Library/Python/2.7/site-packages/huxley/main.py", line 111, in main
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 152, in record
    cls.rerecord(test, path, url, remote_d, sleepfactor, diffcolor, save_diff)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 75, in rerecord
    run._playback(sleepfactor)
  File "/Library/Python/2.7/site-packages/huxley/run.py", line 95, in _playback
    step.execute(self)
  File "/Library/Python/2.7/site-packages/huxley/steps.py", line 40, in execute
    'document.elementFromPoint(%d, %d).click();' % (self.pos[0], self.pos[1])
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 397, in execute_script
    {'script': script, 'args':converted_args})['value']
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/Library/Python/2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 152, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: u'Error Message => \'\'undefined\' is not a function (evaluating \'document.elementFromPoint(744, 257).click()\')\'\n caused by Request => {"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"123","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:7001","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\\"sessionId\\": \\"a23df920-08ff-11e3-bb1a-bbf957ff882c\\", \\"args\\": [], \\"script\\": \\"document.elementFromPoint(744, 257).click();\\"}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/a23df920-08ff-11e3-bb1a-bbf957ff882c/execute"}' ; Screenshot: available via screen 
```

This error happens after you do any clicking on the page.  Looks like it's not able to execute the "click()" function, do you inject jQuery into the DOM anywhere?

**Comment by petehunt** [comment]
Ah, looks like phantom doesn't have `click()`: http://stackoverflow.com/questions/15739263/phantomjs-click-an-element

I think we could probably inject that polyfill and it would work. Can you try adding that to your page to see if it works? If so we can just include it in Huxley.

**Comment by robfe11** [comment]
Just did that actually, replaced line 40 in steps.py with a JS only click event trigger:

```
function eventFire(el,etype){if(el.fireEvent){(el.fireEvent("on"+etype));}else{var evObj=document.createEvent("Events");evObj.initEvent(etype,true,false);el.dispatchEvent(evObj);}}eventFire(document.elementFromPoint(%d, %d),"click");
```

Running into a different problem now!  Seems like phantomJS is taking screenshots using it's own browser, which changes interprets the font size differently (i.e. we are using px instead of em).  This cause xy coordinates to not be consistent across the Chrome browser and phantomjs'.  Trying to see how I can get around that...

**Comment by petehunt** [comment]
Well, that's progress! I do think that x/y is the most reliable way to go and if you could make that work it would be great. If you really can't make that work reliably, another thing you could try is looking at the element you are clicking on and try to construct an xpath expression or something equivalent by traversing its parents and storing that instead. However I really don't like this as one of Huxley's strengths is that it doesn't care about the structure of your DOM and is resilient to refactors.

**Comment by robfe11** [comment]
I agree, using the x/y is the most reliable way, which means that recording in a browser, then executing in a headless browser is not the best solution for that.  So back to the drawing board trying to get Selenium to play nice with forms inside of a modal panel.

**Comment by robfe11** [comment]
Probably not the best solution, but I've been replacing some of your JS calls with jQuery calls to try to narrow down the issue.  Turns out that document.activeElement.id returns null for forms within the modal panel, probably because it wasn't visible when the DOM was loaded.  I'm trying to replace that portion of your code with jQuery, at least for testing.  Anyways, I'll have to continue working on it later this week.

**Comment by petehunt** [comment]
I'm not opposed to injecting jQuery if that's the highest leverage way we can get this to work. Thank you so much for your hard work with this issue -- I'm sure lots of people will benefit from it.

**Comment by robfe11** [comment]
Sorry, been really busy for the past couple months, I have some time coming up, is this something that would still be beneficial for Huxley?
