### ISSUE TITLE
Access error (last.png)

### ISSUE THREAD

**Issue by vfhrr** [facebookarchive/huxley#13]
I tryed to use huxley on windows.

It successfully open firefox browser, take a screenshot. When I enter Q+Enter it start re-run my actions. It succesfully rerecord, but when it start the playback, huxley crashing with next error:

```
Traceback (most recent call last):                                                                      
  File "C:\Users\Plokhov\Envs\test\Scripts\huxley-script.py", line 9, in <module>                
    load_entry_point('Huxley==0.3', 'console_scripts', 'huxley')()                                      
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\cmdline.py", line 150, in main       
    sys.exit(plac.call(_main))                                                                          
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\plac_core.py", line 309, in call            
    cmd, result = parser_from(obj).consume(arglist)                                                     
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\plac_core.py", line 195, in consume         
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)                                      
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\cmdline.py", line 127, in _main      
    screensize=screensize                                                                               
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\main.py", line 109, in main          
    TestRun.record(local_d, d, (url, postdata), screensize, filename, diffcolor, sleepfactor, save_diff)
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\run.py", line 152, in record         
    cls.rerecord(test, path, url, remote_d, sleepfactor, diffcolor, save_diff)                          
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\run.py", line 79, in rerecord        
    cls.playback(test, path, url, d, sleepfactor, diffcolor, save_diff)                                 
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\run.py", line 85, in playback        
    run._playback(sleepfactor)                                                                          
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\run.py", line 95, in _playback       
    step.execute(self)                                                                                  
  File "C:\Users\Plokhov\Envs\test\Lib\site-packages\huxley\steps.py", line 97, in execute       
    os.unlink(new)                                                                                 
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'index.huxley\\last.png'
```

**Comment by dsainati1** [comment]
I also had the same issue just now, with a very similar traceback, the only differences being in the File locations.

**Comment by danielviolin** [comment]
I also had the same issue. My huxley version is 0.4. 
my traceback is here, thx:
Traceback (most recent call last):
  File "C:\Program Files\Python27\Scripts\huxley-script.py", line 9, in <module>

  load_entry_point('Huxley==0.4', 'console_scripts', 'huxley')()
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 153, in main
  File "C:\Program Files\Python27\lib\site-packages\plac_core.py", line 309, in
call
    cmd, result = parser_from(obj).consume(arglist)
  File "C:\Program Files\Python27\lib\site-packages\plac_core.py", line 195, in
consume
    return cmd, self.func(_(args + varargs + extraopts), *_kwargs)
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 130, in _main
  File "build\bdist.win-amd64\egg\huxley\main.py", line 109, in main
  File "build\bdist.win-amd64\egg\huxley\run.py", line 152, in record
  File "build\bdist.win-amd64\egg\huxley\run.py", line 79, in rerecord
  File "build\bdist.win-amd64\egg\huxley\run.py", line 85, in playback
  File "build\bdist.win-amd64\egg\huxley\run.py", line 95, in _playback
  File "build\bdist.win-amd64\egg\huxley\steps.py", line 93, in execute
WindowsError: [Error 32] The process cannot access the file because it is being used by another process: 'toggle
.huxley\last.png'

**Comment by BasJansen** [comment]
Same problem here. Is there a fix or workaround allready? 
When I get this error the record.json file is 0 bytes so all recorded information is lost.

**Comment by charu9** [comment]
One workaround that worked for me. I changed this line in \Python27\Lib\site-packages\huxley\steps.py
in finally block in class ScreenshotTestStep(TestStep) , changed 
           finally:
                if not run.save_diff:
                    os.unlink(new)
TO
         finally:
                if not run.save_diff:
                    print 'end'
