### ISSUE TITLE
Traceback on diff

### ISSUE THREAD

**Issue by mliljedahl** [facebookarchive/huxley#14]
Don't know if it's expected behavior but every time I get a diff huxley gives me a traceback and quits. I have included the output from the example recipe:

```
$ huxley
-------------------------------
Running Huxley file: Huxleyfile
-------------------------------
Running test: toggle
Running test to determine if we need to rerecord
Begin playback
  Sleeping for 2619.0 ms
  Taking screenshot 0
Test failed, rerecording...
Begin rerecord
  Sleeping for 2619.0 ms
  Taking screenshot 0
  Sleeping for 2245.0 ms
  Clicking [116, 79]
  Sleeping for 1355.0 ms
  Taking screenshot 1
  Sleeping for 2365.0 ms
  Clicking [121, 70]
  Sleeping for 1857.0 ms
  Taking screenshot 2

Playing back to ensure the test is correct

Begin playback
  Sleeping for 2619.0 ms
  Taking screenshot 0
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 9, in <module>
    load_entry_point('Huxley==0.3', 'console_scripts', 'huxley')()
  File "/usr/local/lib/python2.7/site-packages/huxley/cmdline.py", line 150, in main
    sys.exit(plac.call(_main))
  File "/usr/local/lib/python2.7/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/usr/local/lib/python2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/usr/local/lib/python2.7/site-packages/huxley/cmdline.py", line 138, in _main
    screensize=screensize
  File "/usr/local/lib/python2.7/site-packages/huxley/main.py", line 129, in main
    TestRun.rerecord(test, filename, (url, postdata), d, sleepfactor, diffcolor, save_diff)
  File "/usr/local/lib/python2.7/site-packages/huxley/run.py", line 79, in rerecord
    cls.playback(test, path, url, d, sleepfactor, diffcolor, save_diff)
  File "/usr/local/lib/python2.7/site-packages/huxley/run.py", line 85, in playback
    run._playback(sleepfactor)
  File "/usr/local/lib/python2.7/site-packages/huxley/run.py", line 95, in _playback
    step.execute(self)
  File "/usr/local/lib/python2.7/site-packages/huxley/steps.py", line 94, in execute
    raise TestError('Screenshot %s was different.' % self.index)
huxley.errors.TestError: Screenshot 0 was different.
```

**Comment by chenglou** [comment]
You can check the screenshot difference with the `--save-diff` flag.
