### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by klausbreyer** [facebookarchive/huxley#21]
I am in the examples directory and huxley crashes. Just installed it. 
localhost:examples kb1$ huxley --record
Traceback (most recent call last):
  File "/usr/local/bin/huxley", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2607, in <module>
    parse_requirements(**requires**), Environment()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: jsonpickle==0.4.0
localhost:examples kb1$

**Comment by davewasmer** [comment]
Had a similar issue, and found that manually installing the dependencies worked (`pip install jsonpickle`).

**Comment by klausbreyer** [comment]
Allready installed all dependencies manually. :(

**Comment by klausbreyer** [comment]
kb1$ sudo pip install --upgrade huxley fixed it

**Comment by petehunt** [comment]
Thanks for the report
