### ISSUE TITLE
Stopping Huxley creates this stacktrace - potential problem?

### ISSUE THREAD

**Issue by CaliLuke** [facebookarchive/huxley#39]
see below

```
Traceback (most recent call last):
  File "/Users/luca/anaconda/bin/huxley", line 9, in <module>
    load_entry_point('Huxley==0.4', 'console_scripts', 'huxley')()
  File "/Users/luca/anaconda/lib/python2.7/site-packages/huxley/cmdline.py", line 153, in main
    sys.exit(plac.call(_main))
  File "/Users/luca/anaconda/lib/python2.7/site-packages/plac_core.py", line 309, in call
    cmd, result = parser_from(obj).consume(arglist)
  File "/Users/luca/anaconda/lib/python2.7/site-packages/plac_core.py", line 195, in consume
    return cmd, self.func(*(args + varargs + extraopts), **kwargs)
  File "/Users/luca/anaconda/lib/python2.7/site-packages/huxley/cmdline.py", line 130, in _main
    screensize=screensize
  File "/Users/luca/anaconda/lib/python2.7/site-packages/huxley/main.py", line 136, in main
    return 0
  File "/Users/luca/anaconda/lib/python2.7/contextlib.py", line 154, in __exit__
    self.thing.close()
  File "/Users/luca/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 445, in close
    self.execute(Command.CLOSE)
  File "/Users/luca/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "/Users/luca/anaconda/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: u"Window not found. The browser window may have been closed.\nCommand duration or timeout: 12 milliseconds\nBuild info: version: '2.39.0', revision: 'ff23eac', time: '2013-12-16 16:11:15'\nSystem info: host: 'lucas-air', ip: '192.168.2.165', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.9.1', java.version: '1.6.0_65'\nSession ID: 6a479e5d-d23a-9a49-86ed-eb58defb4264\nDriver info: org.openqa.selenium.firefox.FirefoxDriver\nCapabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=firefox, rotatable=false, locationContextEnabled=true, version=24.0, cssSelectorsEnabled=true, databaseEnabled=true, handlesAlerts=true, browserConnectionEnabled=true, nativeEvents=false, webStorageEnabled=true, applicationCacheEnabled=true, takesScreenshot=true}]" ; Screenshot: available via screen ; Stacktrace: 
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0 (NativeConstructorAccessorImpl.java:-2)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:513)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable (ErrorHandler.java:193)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed (ErrorHandler.java:145)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:554)
    at org.openqa.selenium.remote.RemoteWebDriver.execute (RemoteWebDriver.java:569)
    at org.openqa.selenium.remote.RemoteWebDriver.close (RemoteWebDriver.java:418)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke (Method.java:597)
    at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke (EventFiringWebDriver.java:101)
    at com.sun.proxy.$Proxy2.close (None:-1)
    at org.openqa.selenium.support.events.EventFiringWebDriver.close (EventFiringWebDriver.java:194)
    at org.openqa.selenium.remote.server.handler.CloseWindow.call (CloseWindow.java:32)
    at org.openqa.selenium.remote.server.handler.CloseWindow.call (CloseWindow.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun (FutureTask.java:303)
    at java.util.concurrent.FutureTask.run (FutureTask.java:138)
    at org.openqa.selenium.remote.server.DefaultSession$1.run (DefaultSession.java:170)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask (ThreadPoolExecutor.java:895)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:918)
    at java.lang.Thread.run (Thread.java:695) 
```

**Comment by petehunt** [comment]
This is probably OK. Are you seeing any related issues?

**Comment by CaliLuke** [comment]
yeah, the problem is that the JSON file containing the steps is completely empty. Screenshots are saved successfully.

**Comment by petehunt** [comment]
This is strange. Do you have specific repro steps?
