### ISSUE TITLE
How Could I use huxley with proxy?

### ISSUE THREAD

**Issue by hugoxie** [facebookarchive/huxley#40]
I want to use huxley to test my website, but my company have set the firewall, so I must set a proxy to open my website by urlopen.
 How can I do?

**Comment by petehunt** [comment]
Try setting the `http_proxy` environment variable before running. Does that work?

**Comment by hugoxie** [comment]
@petehunt  Thank you! I'll try it today. I wonder that is huxley provide some option to set proxy. if it doesn't. I'll try another way.

**Comment by petehunt** [comment]
Did this end up working?

**Comment by hugoxie** [comment]
@petehunt  set http_proxy is work, it didn't report urlopen error anymore, but I got another problem, it said: 'UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 193: invalid start byte',
what's the matter

**Comment by petehunt** [comment]
Can you paste the full trace back?

**Comment by hugoxie** [comment]
@petehunt   

Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Python27\lib\threading.py", line 810, in **bootstrap_inner
    self.run()
  File "E:\Python27\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "build\bdist.win-amd64\egg\huxley\threadpool.py", line 32, in thread
    func(_args, *_kwargs)
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 69, in run_test
    screensize=screensize
  File "build\bdist.win-amd64\egg\huxley\main.py", line 83, in main
    d = webdriver.Remote(remote, CAPABILITIES[browser])
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 72, in __init**
    self.start_session(desired_capabilities, browser_profile)
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 114, in start_session
    'desiredCapabilities': desired_capabilities,
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 163, in execute
    response = self.command_executor.execute(driver_command, params)
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\remote_connection.py", line 353, in execute
    return self._request(url, method=command_info[0], data=data)
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\remote_connection.py", line 404, in _request
    body = response.read().decode('utf-8').replace('\x00', '').strip()
  File "E:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb4 in position 193: invalid
 start byte

**Comment by hugoxie** [comment]
@petehunt I've print the response.read(), but it seems that open website error, the information show that Connection refused. 
I try set http_proxy and use urllib2.urlopen to open the same website in python cmd mode, the response is the ok.
I feel puzzled.
