### ISSUE TITLE
After taken screenshots q+enter exit huxley report error and record.json file is empty

### ISSUE THREAD

**Issue by hugoxie** [facebookarchive/huxley#49]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Python27\lib\threading.py", line 810, in **bootstrap_inner
    self.run()
  File "E:\Python27\lib\threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "build\bdist.win-amd64\egg\huxley\threadpool.py", line 32, in thread
    func(_args, *_kwargs)
  File "build\bdist.win-amd64\egg\huxley\cmdline.py", line 69, in run_test
    screensize=screensize
  File "build\bdist.win-amd64\egg\huxley\main.py", line 137, in main
    return 0
  File "E:\Python27\lib\contextlib.py", line 154, in __exit**
    self.thing.close()
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 445, in close
    self.execute(Command.CLOSE)
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\webdriver.py", line 165, in execute
    self.error_handler.check_response(response)
  File "E:\Python27\lib\site-packages\selenium-2.35.0-py2.7.egg\selenium\webdriv
er\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: u"Error communicating with the remote browser. It m
ay have died.\nBuild info: version: '2.39.0', revision: 'ff23eac', time: '2013-1
2-16 16:11:15'\nSystem info: host: 'hugoxie-PC0', ip: '10.33.64.52', os.name: 'W
indows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.7.0_45'\nDriver
 info: driver.version: EventFiringWebDriver" ; Stacktrace:

**Comment by hugoxie** [comment]
selenium report error too.

it said:
Caused by: org.openqa.selenium.remote.ErrorHandler$UnknownServerException: windo
w._getHuxleyEvents is not a function

**Comment by chenglou** [comment]
^ This usually means you've navigated away from a page. Currently, Huxley records what's on the initial page only, as it injects a script during page start to track your actions.
There might be some use cases for navigating to another page, but I'd say usually when you're testing single components, you should be fine.

**Comment by hugoxie** [comment]
hi，chenglou，thanks for your comment, when I record only one page, q+enter to finish record, on windows huxley write record.json error by decode error. the default encode is gbk on my system. where can I fixed the problem

**Comment by chenglou** [comment]
Cool, so this is a different issue right? Can you open a new one? Easier to diagnose this way.

**Comment by hugoxie** [comment]
OK, franks
