### ISSUE TITLE
Huxley record session fails with null exception

### ISSUE THREAD

**Issue by jhulme** [facebookarchive/huxley#62]
I'm having a problem when attempting to start a fresh record with Huxley. The exception error returned is below:

```
------------------------------------
Running Huxley file: huxtestfile.txt
------------------------------------
[login] Running test: login
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\Lib\threading.py", line 808, in __bootstrap_inner
    self.run()
  File "C:\Python27\Lib\threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-        packages\huxley\threadpool.py", line 32, in thread
    func(*args, **kwargs)
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\huxley\cmdline.py", line 69, in run_test
    screensize=screensize
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\huxley\main.py", line 83, in main
    d = webdriver.Remote(remote, CAPABILITIES[browser])
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 72, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 115, in start_session
    'desiredCapabilities': desired_capabilities,
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 166, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Test\projects\net10-test\net10-test\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 164, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: None ; Stacktrace:
```

I have installed Huxley into a python virtualenv and ensured that the selenium server is running before attempting to start the record. My huxley file is a very basic:

```
[login]
url=http://2.2.2.2/login.html
```

I've confirmed my web application is accessible from Firefox (using the above URL) and I can navigate to 127.0.0.1:4444/wd/hub successfully.

Checking the response in Fiddler shows POST request contains a NULL value for the sessionID. The resulting NullPointerException error appears to be the root cause of my Unknown Error.

```
{"sessionId":null,"status":13,"value":    {"message":null,"localizedMessage":null,"suppressed":    [],"cause":null,"class":"java.lang.NullPointerException","hCode":3963113,"stackTrace":    [null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,    null,null,null,null,null,null]},"state":"unhandled     error","class":"org.openqa.selenium.remote.Response","hCode":2501105}
```

Any help would be much appreciated.

Cheers.

**Comment by jhulme** [comment]
Issue was resolved by updating Selenium to latest version and then subsequently altering huxley - requires.txt file as per issue #42.

This item can be closed off.
